config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:index,:new, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  has_many  :likes

  def iine(user)
    likes.create(user_id: user.id)
  end
  
  def iine?(user)
    iine_users.include?(user)
  end
  
  def uniine(user)
    likes.find_by(user_id: user.id).destroy
  end

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  skip_before_action :verify_authenticity_token
  
  def new
    @micropost = current_user.microposts.new
    @feed_items = current_user.feed.paginate(page: params[:page])
  end


  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture, :song, :artist, :like)
    end

    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_action.html.erb
<% if like = Like.find_by(user_id: current_user.id, micropost_id: micropost.id) %>
    <%= link_to micropost_like_path(micropost_id: like.micropost.id,id: like.id), method: :delete, remote: :true, :class => "clicked", :style => "margin-left:1em" do %>
        <p class="action">👏<%= micropost.likes.count %></p>
    <% end %>
<% else %>
    <%= link_to micropost_likes_path(micropost.id), method: :post, remote: :true, :style => "margin-left:1em" do %>
        <p class="action">👏<%= micropost.likes.count %></p>
    <% end %>
<% end %><!-- Like -->

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <div class = tweet>
    <div class = target>
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    </div>
    <div class = user>
      <%= link_to micropost.user.name, micropost.user %>
      <%= micropost.created_at.strftime("%Y/%m/%d %H:%M") %>
    </div>
    <div class = song>曲名:  <%= link_to micropost.song, "https://www.youtube.com/results?search_query=#{micropost.song}" %></div>
    <div class = artist>アルバム名: <%= link_to micropost.artist, "https://www.youtube.com/results?search_query=#{micropost.artist}" %></div>
    <div class = content>感想:  <%= micropost.content %></div>
    <div class = picture><%= image_tag micropost.picture.url if micropost.picture? %></div>
    <div id="likes_buttons_<%= micropost.id %>">
    <% if current_user.present? %>
				<%= render :partial => "microposts/action", :locals => { micropost: micropost } %>
		</div>
		<% else %><!-- authorized -->
				<%= link_to micropost_likes_path(micropost.id)  ,method: :post, :style => "margin-left:1em" do %>
				  <p class="action">👆<%= micropost.likes.count %></p>
				<% end %>
		<%= render 'users/follow_form', :locals => { micropost: micropost }  if logged_in? %>
		    <% end %>
    <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, method: :delete,
                                         data: { confirm: "削除してよろしいですか?" } %>
    <% end %>
      </div>
  </span>
</li>

app/views/microposts/new.html.erb
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>